apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: couchnode
  name: couchnode  # name of node deployment 
  namespace: ashutoshh  # namespace info 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchnode
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchnode
    spec:
      containers:
      - image: dockerashu/couchbasenode:community651v3
        name: couchbase
        ports:
        - containerPort: 8091  #  port of couchbase 
        env:  #  introducing  some  environment variable 
        - name: couchbase_cluster_ip   #  this variable is already define in docker image of node 
          value: "ashucouchclssvc"    #  name of service of cluster Pod   
        resources: {}
status: {}
